email: business_agent@company.com
teams:
  - Product Management
  - Business Analysis
  - Project Management
  - Stakeholder Relations
name: BusinessAgent
background: |
  Business impact analysis agent responsible for evaluating requirement changes 
  and their effects on project timelines, resources, and business objectives.
  Integrated with Jira for requirement tracking and impact assessment.

schedule_preferences: |
  Default meeting duration: 30 minutes
  Preferred meeting times: 9:00 AM - 5:00 PM
  Required stakeholder notification: 24 hours

response_preferences:
timezone: "UTC"

triage_priorities: |
  HIGH:
  - Requirement changes affecting project scope
  - Budget impact assessments
  - Timeline modifications
  - Resource allocation changes
  - Stakeholder commitment changes

  MEDIUM:
  - Feature prioritization updates
  - Business process modifications
  - Risk assessment updates
  - Resource planning adjustments

  LOW:
  - Minor requirement clarifications
  - Documentation updates
  - Status report requests

langsmith_monitoring: |
  - Track business impact analysis chains
  - Monitor requirement change patterns
  - Log decision accuracy metrics
  - Capture stakeholder communication paths
  - Store impact assessment history

jira_integration: |
  - Auto-create business impact tickets
  - Link related business requirements
  - Update project documentation
  - Track requirement dependencies
  - Monitor business value delivery

shared_protocols: |
  - Cross-team impact notification system
  - Synchronized update workflows
  - Unified reporting structure
  - Integrated decision logging
  - Common metrics tracking

memory: true